# Generated by Django 3.2.16 on 2023-01-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0002_alter_feedback_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
